---
apiVersion: v2
name: kube-prometheus-stack
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    # TODO: Upgrade to a newer chart that doesn't suffer issues
    # https://github.com/prometheus-community/helm-charts/issues/1500
    version: 19.3.0
    repository: https://prometheus-community.github.io/helm-charts
