---
kube-prometheus-stack:
  grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100

  kubeEtcd:
    # Disabled for managed Kubernetes services
    enabled: false

  kubeControllerManager:
    # Disabled for managed Kubernetes services
    enabled: false

  kubeScheduler:
    # Disabled for managed Kubernetes services
    enabled: false
